[global]
server_name = "nutra.tk"
database_path = "/var/lib/matrix-conduit/"
database_backend = "rocksdb"
port = 6167
address = "127.0.0.1"
max_request_size = 20_000_000 # 20MB
allow_registration = true
allow_federation = true
trusted_servers = ["matrix.org"]

[log]
# For more info on this, check out https://docs.rs/env_logger/latest/env_logger/#enabling-logging
filter = "warn"
